blank_issues_enabled: true
contact_links:
  - name: Report a security issue
    url: https://github.com/ariaieboy/filament-currency/security/policy
    about: Learn how to notify us for sensitive bugs
